name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (via JFrog)
      run: ./mvnw clean package -DskipTests

    - name: Install JFrog CLI v2
      run: |
        curl -fL -o jf https://releases.jfrog.io/artifactory/jfrog-cli/v2/latest/jfrog-cli-linux-amd64/jf
        chmod +x jf
        sudo mv jf /usr/local/bin/jf
        jf --version

    - name: Configure JFrog CLI
      env:
        JFROG_URL: ${{ secrets.JFROG_URL }}
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      run: |
        jf config add jfrog-server \
          --artifactory-url=$JFROG_URL \
          --user=$JFROG_USER \
          --password=$JFROG_API_KEY \
          --interactive=false

    - name: Build Docker Image
      run: docker build -t petclinic:latest .

    - name: Tag and Push Docker Image to JFrog
      env:
        JFROG_DOCKER_URL: ${{ secrets.JFROG_DOCKER_URL }}
      run: |
        docker tag petclinic:latest $JFROG_DOCKER_URL/petclinic:latest
        docker push $JFROG_DOCKER_URL/petclinic:latest

    - name: Push Docker Image with Build Info
      env:
        JFROG_DOCKER_URL: ${{ secrets.JFROG_DOCKER_URL }}
      run: |
        jf docker push $JFROG_DOCKER_URL/petclinic:latest \
          --build-name=petclinic-ci \
          --build-number=${{ github.run_number }}

    - name: Publish Build Info
      run: jf rt build-publish petclinic-ci ${{ github.run_number }}

    - name: Xray Scan Build
      run: jf xr build-scan petclinic-ci ${{ github.run_number }}

